server:
  port: 1920
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database_analysis_and_design?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}  # 改为系统临时目录，避免使用源码目录
  # 新增静态资源配置
  web:
    resources:
      static-locations:
          classpath:/static/,
          file:./uploads/dynamic/  # 精确到动态子目录
  mvc:
     static-path-pattern: /**
  favcon:
     enabled: false

logging:
  level:
    org.springframework.web: DEBUG
debug: true

wechat:
  appid: wx8724e884f1d63e
  secret: e7913ed68d23112a3cf73c739de70633

jwt:
  secret: your-secret-key-12345
  expiration: 86400000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: org.travelsystem.travel.entity

file:
  upload:
    path: uploads # 改为项目相对路径（非源码目录）
    allowed-types: image/jpeg,image/png,image/webp,application/pdf
    max-size: 10MB